#!/bin/sh

mkdir -p opk
cp ./temper opk/temper
cp ./icon.png opk/icon.png

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=Temper
Comment=PC-Engine emulator
Exec=temper %f
Icon=icon
Terminal=false
Type=Application
Categories=emulators;
X-OD-NeedsDownscaling=false' > opk/default.rs90.desktop

mksquashfs ./opk temper_rs90.opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
